server:
  port: 9191
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            -   id: EMPLOYEE-SERVICE
                predicates:
                  - Path=/api/v1/employees/**
                uri: lb://EMPLOYEE-SERVICE
            -   id: DEPARTMENT-SERVICE
                predicates:
                  - Path=/api/v1/departments/**
                uri: lb://DEPARTMENT-SERVICE
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedMethods: GET, POST, PUT, DELETE
                allowedOrigins: '*'

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
