eureka:
  instance:
    client:
      register-with-eureka: true
      fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always    
