spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10     # Maksimum es zamanli baglanti sayisi
      minimum-idle: 2           # Hazirda bekleyen minimum baglanti
      idle-timeout: 30000       # Bosta kalan baglantinin kapatilma suresi (ms)
      max-lifetime: 1800000     # Baglantinin maksimum omru (ms)
      connection-timeout: 20000 # Baglanti isteginin zaman asimi suresi (ms)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 2
        max-concurrency: 10
        default-requeue-rejected: true
    publisher-confirm-type: correlated
    publisher-returns: true
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web

info:
  app:
    name: employee-services microservices workshop
    description: microservices springboot workshop
    version: 0.0.1

server:
  port: 8081

department:
  service:
    url: http://localhost:8080/api/v1/departments/code/
  
eureka:
  instance:
    client:
      register-with-eureka: true
      fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always 
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
  health:
    circuitbreakers:
      enabled: true
    
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      springframework:
        web: DEBUG
        
resilience4j:
  circuitbreaker:
    instances:
      employee-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      employee-service:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 2s

service:
  module:
    version: Ver. 0.0.2
